#!/usr/bin/env bash

if [ "$1" = "-k" ]; then
  tvname=2
else
  tvname=\"$1\"
fi

read -d '' APPLESCRIPT <<EOF
tell application "System Events"
    tell process "SystemUIServer"
            tell (menu bar item 1 of menu bar 1 whose description contains "Displays Menu")
				select
				delay 0.5
				key code 125 using command down
				delay 0.5
				click menu item $tvname of menu 1
			end tell
    end tell
end tell
EOF

osascript -e "$APPLESCRIPT" > /dev/null
