#!/usr/bin/env bash

if [ "$1" = "-k" ]; then
  tvname=2
else
  tvname=\"$1\"
fi

read -d '' APPLESCRIPT <<EOF
tell application "System Events"
    tell process "SystemUIServer"
            click (menu bar item 1 of menu bar 1 whose description contains "Displays")
            click menu item $tvname of menu 1 of result
    end tell
end tell
EOF

osascript -e "$APPLESCRIPT" > /dev/null
